import { Tool } from './types';

export const TOOLS: Tool[] = [
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate high-quality QR codes for any text, URL, or contact information instantly.',
    shortDescription: 'Text to QR Code',
    icon: 'QrCode',
    category: 'generator',
    path: '/qr-generator',
  },
  {
    id: 'whatsapp-link',
    name: 'WhatsApp Link Generator',
    description: 'Create direct WhatsApp chat links with pre-filled messages for your business or personal use.',
    shortDescription: 'Chat links',
    icon: 'MessageSquare',
    category: 'generator',
    path: '/whatsapp-link',
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate your exact age in years, months, and days from your date of birth.',
    shortDescription: 'Find your age',
    icon: 'Calendar',
    category: 'calculator',
    path: '/age-calculator',
  },
  {
    id: 'gst-calculator',
    name: 'GST Calculator',
    description: 'Add or remove GST from your prices with multiple percentage options.',
    shortDescription: 'Tax calculations',
    icon: 'Percent',
    category: 'calculator',
    path: '/gst-calculator',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure, random passwords with customizable length and complexity.',
    shortDescription: 'Secure passwords',
    icon: 'Lock',
    category: 'generator',
    path: '/password-generator',
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, and estimate reading time for your text content.',
    shortDescription: 'Text analysis',
    icon: 'FileText',
    category: 'text',
    path: '/word-counter',
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate your Body Mass Index (BMI) and find your health category.',
    shortDescription: 'Health check',
    icon: 'Activity',
    category: 'calculator',
    path: '/bmi-calculator',
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Easily calculate percentages, increases, decreases, and differences.',
    shortDescription: 'Quick math',
    icon: 'Calculator',
    category: 'calculator',
    path: '/percentage-calculator',
  },
  {
    id: 'emi-calculator',
    name: 'EMI Calculator',
    description: 'Plan your loans by calculating monthly EMIs based on amount, rate, and tenure.',
    shortDescription: 'Loan planning',
    icon: 'CreditCard',
    category: 'calculator',
    path: '/emi-calculator',
  },
  {
    id: 'text-case',
    name: 'Text Case Converter',
    description: 'Convert your text to UPPERCASE, lowercase, Capitalized, and more.',
    shortDescription: 'Case conversion',
    icon: 'Type',
    category: 'text',
    path: '/text-case',
  },
  {
    id: 'character-counter',
    name: 'Character Counter',
    description: 'Detailed character counting with space inclusion and social media limit indicators.',
    shortDescription: 'Live counting',
    icon: 'Hash',
    category: 'text',
    path: '/character-counter',
  },
  {
    id: 'random-number',
    name: 'Random Number Generator',
    description: 'Generate a random number within your specified minimum and maximum range.',
    shortDescription: 'Roll the dice',
    icon: 'Dices',
    category: 'utility',
    path: '/random-number',
  },
];
